import type {
  User,
  Project,
  Record,
  RequiredAction,
  ProgrammeImpact,
  CostImpact,
  Stakeholder,
} from './types';
import {
  USER_ROLES,
} from './constants';

const randomItem = <T,>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];
const d = (value: string) => new Date(`${value}T10:00:00`);

// Users
export function generateMockUsers(): User[] {
  const roleDescriptions = {
    PM: 'Oversees project records and decisions',
    DC: 'Logs, tags, and routes correspondence',
    PT: 'Reviews delay and schedule impact',
    CT: 'Reviews cost impact and claim risk',
    CE: 'Reviews instructions and approvals',
    ADMIN: 'System administration',
  };

  return [
    { id: '1', name: 'Ahmed Al-Rashid', role: 'PM', email: 'ahmed.rashid@construct.jo', avatar: '👨‍💼' },
    { id: '2', name: 'Fatima Al-Manaseer', role: 'DC', email: 'fatima.manaseer@construct.jo', avatar: '👩‍🔬' },
    { id: '3', name: 'Mohammed Al-Dajani', role: 'PT', email: 'mohammed.dajani@construct.jo', avatar: '👨‍🔧' },
    { id: '4', name: 'Aisha Al-Masri', role: 'CT', email: 'aisha.masri@construct.jo', avatar: '👩‍⚖️' },
    { id: '5', name: 'Hassan Al-Omari', role: 'CE', email: 'hassan.omari@construct.jo', avatar: '👨‍🏫' },
    { id: '6', name: 'Layla Al-Zu\'bi', role: 'ADMIN', email: 'layla.zubi@construct.jo', avatar: '👩‍💻' },
  ];
}

// Projects
export function generateMockProjects(): Project[] {
  const projects: Project[] = [
    {
      id: 'p1',
      name: 'Amman Business Tower',
      client: 'Al-Faisaliah Investment',
      contractType: 'FIDIC Pink - Design Build',
      location: 'Amman, Jordan',
      status: 'Active',
      startDate: new Date('2024-01-15'),
      endDate: new Date('2026-03-31'),
      totalRecords: 7,
      openActions: 5,
      overdueItems: 2,
      costImpactRecords: 2,
      programmeImpactRecords: 2,
      claimRiskItems: 1,
      lastActivity: new Date(),
      stakeholders: [
        { id: 's1', name: 'Ahmed Al-Rashid', role: 'Project Manager' },
        { id: 's2', name: 'Fatima Al-Manaseer', role: 'Design Lead' },
        { id: 's3', name: 'Mohammed Al-Dajani', role: 'Quality Manager' },
      ],
    },
    {
      id: 'p2',
      name: 'Aqaba Marina Resort',
      client: 'Beach Development Corp',
      contractType: 'FIDIC Yellow - Lump Sum',
      location: 'Aqaba, Jordan',
      status: 'At Risk',
      startDate: new Date('2023-06-01'),
      endDate: new Date('2025-12-15'),
      totalRecords: 4,
      openActions: 3,
      overdueItems: 1,
      costImpactRecords: 1,
      programmeImpactRecords: 2,
      claimRiskItems: 1,
      lastActivity: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      stakeholders: [
        { id: 's4', name: 'Hassan Al-Omari', role: 'Civil Engineer' },
        { id: 's5', name: 'Aisha Al-Masri', role: 'Contracts Manager' },
      ],
    },
    {
      id: 'p3',
      name: 'Irbid Hospital Extension',
      client: 'Ministry of Health',
      contractType: 'FIDIC Green - Cost Plus',
      location: 'Irbid, Jordan',
      status: 'Monitoring',
      startDate: new Date('2024-03-01'),
      endDate: new Date('2025-09-30'),
      totalRecords: 3,
      openActions: 2,
      overdueItems: 0,
      costImpactRecords: 1,
      programmeImpactRecords: 0,
      claimRiskItems: 0,
      lastActivity: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      stakeholders: [
        { id: 's6', name: 'Layla Al-Zu\'bi', role: 'Administrator' },
        { id: 's7', name: 'Ahmed Al-Rashid', role: 'Project Manager' },
      ],
    },
    {
      id: 'p4',
      name: 'Dead Sea Spa Complex',
      client: 'Luxury Hospitality Ltd',
      contractType: 'FIDIC Red - Admeasurement',
      location: 'Dead Sea, Jordan',
      status: 'Closed',
      startDate: new Date('2022-09-01'),
      endDate: new Date('2024-06-30'),
      totalRecords: 2,
      openActions: 0,
      overdueItems: 0,
      costImpactRecords: 1,
      programmeImpactRecords: 0,
      claimRiskItems: 0,
      lastActivity: new Date('2024-06-25'),
      stakeholders: [
        { id: 's8', name: 'Mohammed Al-Dajani', role: 'Quality Manager' },
      ],
    },
  ];

  return projects;
}

// Records
type RecordSeed = Omit<Record, 'createdAt' | 'updatedAt' | 'comments' | 'actionHistory'> & {
  createdAt?: Date;
  updatedAt?: Date;
};

const baseRecord = (seed: RecordSeed): Record => {
  const createdAt = seed.createdAt || seed.dateReceived;
  return {
    ...seed,
    createdAt,
    updatedAt: seed.updatedAt || seed.dateReceived,
    comments: [
      {
        id: `${seed.id}-comment-1`,
        author: seed.createdBy,
        text: `Logged with ${seed.mainCategory} / ${seed.discipline} tags and routed to ${seed.responsibleParty || 'the project team'}.`,
        createdAt,
      },
    ],
    actionHistory: [
      {
        id: `${seed.id}-hist-1`,
        action: 'Record logged and classified',
        performedBy: seed.createdBy,
        timestamp: createdAt,
        newValue: seed.status,
      },
      ...(seed.actionStatus
        ? [{
            id: `${seed.id}-hist-2`,
            action: 'Action status updated',
            performedBy: seed.responsibleParty || seed.createdBy,
            timestamp: seed.updatedAt || seed.dateReceived,
            newValue: seed.actionStatus,
          }]
        : []),
    ],
  };
};

const attachment = (recordId: string, name: string, uploadedAt: Date, uploadedBy: string) => ({
  id: `${recordId}-att-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  name,
  size: 420000,
  type: name.endsWith('.pdf') ? 'application/pdf' : name.endsWith('.dwg') ? 'application/dwg' : 'image/jpeg',
  uploadedAt,
  uploadedBy,
});

export function generateMockRecords(): Record[] {
  return [
    baseRecord({
      id: 'rec-0001',
      reference: 'CORR-2026-001',
      title: 'Site Issue - Level 3 MEP Ductwork Clash',
      projectId: 'p1',
      sender: 'MEP Subcontractor',
      receiver: 'Main Contractor',
      dateReceived: d('2026-05-12'),
      description: 'MEP subcontractor reported that the approved duct route clashes with the post-tension slab beam at Level 3 grid C4-C6. Ceiling framing and chilled-water pipe supports cannot proceed until revised coordination drawings are issued.',
      mainCategory: 'Site Issue',
      subcategory: 'MEP/Civil/Architectural Issue',
      discipline: 'MEP',
      priority: 'Critical',
      status: 'Pending Response',
      eventDate: d('2026-05-11'),
      responseDueDate: d('2026-05-17'),
      linkedVariations: ['rec-0004'],
      linkedDelays: ['rec-0003'],
      linkedInstructions: ['rec-0002'],
      linkedApprovals: ['rec-0006'],
      linkedCostImpacts: ['rec-0005'],
      linkedProgrammeImpacts: ['rec-0003'],
      linkedClaimRisks: ['rec-0007'],
      linkedSiteIssues: [],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: true,
      programmeImpactDesc: 'Potential 7-day critical path delay to Level 3 ceiling close-out.',
      hasCostImpact: true,
      costImpactDesc: 'Additional supports, duct offsets, and rework labour expected.',
      estimatedAmount: 127800,
      hasClaimRisk: true,
      claimRiskLevel: 'High',
      claimRiskNotes: 'Notice required if revised instruction is not issued within the response period.',
      responsibleParty: 'Hassan Al-Omari',
      requiredAction: 'Issue coordinated MEP routing response for Level 3 clash',
      actionDueDate: d('2026-05-17'),
      actionStatus: 'Overdue',
      nextStep: 'Engineer to confirm revised routing and commercial team to preserve notice rights.',
      createdBy: 'Fatima Al-Manaseer',
      attachments: [attachment('rec-0001', 'CORR-2026-001 Level 3 Clash Photos.jpg', d('2026-05-12'), 'MEP Subcontractor')],
    }),
    baseRecord({
      id: 'rec-0002',
      reference: 'EI-2026-015',
      title: "Engineer's Instruction - Revised MEP Routing",
      projectId: 'p1',
      sender: 'Consultant / Engineer',
      receiver: 'Main Contractor',
      dateReceived: d('2026-05-14'),
      description: 'Engineer instructed the contractor to reroute supply ductwork around the structural beam and submit revised shop drawings within 48 hours. Instruction references the Level 3 site issue and requires no ceiling closure until acceptance.',
      mainCategory: 'Instruction',
      subcategory: "Engineer's Instruction",
      discipline: 'MEP',
      priority: 'High',
      status: 'Open',
      eventDate: d('2026-05-14'),
      instructionDate: d('2026-05-14'),
      responseDueDate: d('2026-05-16'),
      linkedVariations: ['rec-0004'],
      linkedDelays: ['rec-0003'],
      linkedInstructions: [],
      linkedApprovals: ['rec-0006'],
      linkedCostImpacts: ['rec-0005'],
      linkedProgrammeImpacts: ['rec-0003'],
      linkedClaimRisks: ['rec-0007'],
      linkedSiteIssues: ['rec-0001'],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: true,
      programmeImpactDesc: 'Instruction requires redesign before Level 3 activity can restart.',
      hasCostImpact: true,
      costImpactDesc: 'Instruction is linked to variation valuation for additional duct offsets.',
      estimatedAmount: 127800,
      hasClaimRisk: true,
      claimRiskLevel: 'Medium',
      claimRiskNotes: 'Instruction may support variation entitlement if substantiated.',
      responsibleParty: 'Ahmed Al-Rashid',
      requiredAction: 'Submit revised MEP shop drawing package for EI-015',
      actionDueDate: d('2026-05-16'),
      actionStatus: 'Waiting for Response',
      nextStep: 'Document controller to route revised shop drawing to consultant.',
      createdBy: 'Fatima Al-Manaseer',
      attachments: [attachment('rec-0002', 'EI-015 Revised MEP Routing.pdf', d('2026-05-14'), 'Consultant / Engineer')],
    }),
    baseRecord({
      id: 'rec-0003',
      reference: 'DLY-2026-003',
      title: 'Programme Impact - Level 3 Ceiling Works Delay',
      projectId: 'p1',
      sender: 'Planning Team',
      receiver: 'Project Manager',
      dateReceived: d('2026-05-15'),
      description: 'Planner recorded a 7-calendar-day impact to Level 3 ceiling close-out because MEP rerouting approval blocks ceiling framing, inspection, and boarding activities on the current baseline sequence.',
      mainCategory: 'Delay',
      subcategory: 'Delay Issue',
      discipline: 'Planning',
      priority: 'High',
      status: 'In Review',
      eventDate: d('2026-05-15'),
      responseDueDate: d('2026-05-18'),
      linkedVariations: ['rec-0004'],
      linkedDelays: [],
      linkedInstructions: ['rec-0002'],
      linkedApprovals: ['rec-0006'],
      linkedCostImpacts: ['rec-0005'],
      linkedProgrammeImpacts: [],
      linkedClaimRisks: ['rec-0007'],
      linkedSiteIssues: ['rec-0001'],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: true,
      programmeImpactDesc: '7 days on fit-out critical path, subject to mitigation by resequencing.',
      hasCostImpact: false,
      hasClaimRisk: true,
      claimRiskLevel: 'Medium',
      claimRiskNotes: 'Delay notice to be preserved if approval remains outstanding.',
      responsibleParty: 'Mohammed Al-Dajani',
      requiredAction: 'Update programme narrative and mitigation options',
      actionDueDate: d('2026-05-18'),
      actionStatus: 'Pending Review',
      nextStep: 'Planner to issue Programme Update Rev. 07 with cause-and-effect narrative.',
      createdBy: 'Mohammed Al-Dajani',
      attachments: [attachment('rec-0003', 'Programme Update Rev 07 Extract.pdf', d('2026-05-15'), 'Planning Team')],
    }),
    baseRecord({
      id: 'rec-0004',
      reference: 'VAR-2026-014',
      title: 'Variation - Additional Ductwork Offsets and Supports',
      projectId: 'p1',
      sender: 'Main Contractor',
      receiver: 'Commercial / QS Team',
      dateReceived: d('2026-05-17'),
      description: 'Contractor submitted variation notice for additional duct offsets, supports, access panels, and coordination labour arising from EI-015. Submission references measured quantities and labour records from Level 3.',
      mainCategory: 'Variation',
      subcategory: 'Drawing/Spec Variation',
      discipline: 'Commercial',
      priority: 'High',
      status: 'Open',
      eventDate: d('2026-05-17'),
      instructionDate: d('2026-05-14'),
      responseDueDate: d('2026-05-24'),
      linkedVariations: [],
      linkedDelays: ['rec-0003'],
      linkedInstructions: ['rec-0002'],
      linkedApprovals: ['rec-0006'],
      linkedCostImpacts: ['rec-0005'],
      linkedProgrammeImpacts: ['rec-0003'],
      linkedClaimRisks: ['rec-0007'],
      linkedSiteIssues: ['rec-0001'],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: true,
      programmeImpactDesc: 'Variation linked to Level 3 delay event.',
      hasCostImpact: true,
      costImpactDesc: 'JOD 127,800 submitted for additional material, supports, and labour.',
      estimatedAmount: 127800,
      hasClaimRisk: true,
      claimRiskLevel: 'High',
      claimRiskNotes: 'Commercial entitlement depends on timely instruction and evidence trail.',
      responsibleParty: 'Aisha Al-Masri',
      requiredAction: 'Review variation substantiation and issue QS recommendation',
      actionDueDate: d('2026-05-24'),
      actionStatus: 'Open',
      nextStep: 'QS to compare measured quantities against revised drawing and site records.',
      createdBy: 'Aisha Al-Masri',
      attachments: [attachment('rec-0004', 'VAR-2026-014 Quantity Build-Up.xlsx', d('2026-05-17'), 'Commercial / QS Team')],
    }),
    baseRecord({
      id: 'rec-0005',
      reference: 'CI-2026-011',
      title: 'Cost Impact - Level 3 MEP Rework',
      projectId: 'p1',
      sender: 'Commercial / QS Team',
      receiver: 'Project Manager',
      dateReceived: d('2026-05-18'),
      description: 'QS assessment records JOD 127,800 provisional exposure for duct offsets, additional supports, weekend labour, and ceiling trade standby linked to the Level 3 coordination change.',
      mainCategory: 'Cost Impact',
      subcategory: 'Variation Cost',
      discipline: 'Commercial',
      priority: 'High',
      status: 'In Review',
      eventDate: d('2026-05-18'),
      responseDueDate: d('2026-05-25'),
      linkedVariations: ['rec-0004'],
      linkedDelays: ['rec-0003'],
      linkedInstructions: ['rec-0002'],
      linkedApprovals: ['rec-0006'],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: ['rec-0003'],
      linkedClaimRisks: ['rec-0007'],
      linkedSiteIssues: ['rec-0001'],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: true,
      programmeImpactDesc: 'Cost exposure tied to delay mitigation labour.',
      hasCostImpact: true,
      costImpactDesc: 'JOD 127,800 provisional assessment.',
      estimatedAmount: 127800,
      hasClaimRisk: true,
      claimRiskLevel: 'Medium',
      claimRiskNotes: 'Claim risk moderate if consultant approval is delayed beyond due date.',
      responsibleParty: 'Aisha Al-Masri',
      requiredAction: 'Submit cost substantiation package with supporting site records',
      actionDueDate: d('2026-05-25'),
      actionStatus: 'Pending Review',
      nextStep: 'Attach labour allocation sheets and revised drawing markups.',
      createdBy: 'Aisha Al-Masri',
      attachments: [attachment('rec-0005', 'CI-011 Cost Summary.pdf', d('2026-05-18'), 'Commercial / QS Team')],
    }),
    baseRecord({
      id: 'rec-0006',
      reference: 'AP-2026-004',
      title: 'Approval - Revised MEP Shop Drawing S3-MEP-221',
      projectId: 'p1',
      sender: 'Document Controller',
      receiver: 'Consultant / Engineer',
      dateReceived: d('2026-05-19'),
      description: 'Document controller transmitted revised MEP shop drawing S3-MEP-221 for consultant approval. The package includes clash markup, revised route, and contractor response to EI-015.',
      mainCategory: 'Approval',
      subcategory: 'Drawing Approval',
      discipline: 'MEP',
      priority: 'High',
      status: 'Pending Response',
      eventDate: d('2026-05-19'),
      responseDueDate: d('2026-05-23'),
      linkedVariations: ['rec-0004'],
      linkedDelays: ['rec-0003'],
      linkedInstructions: ['rec-0002'],
      linkedApprovals: [],
      linkedCostImpacts: ['rec-0005'],
      linkedProgrammeImpacts: ['rec-0003'],
      linkedClaimRisks: ['rec-0007'],
      linkedSiteIssues: ['rec-0001'],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: true,
      programmeImpactDesc: 'Approval timing controls restart of Level 3 works.',
      hasCostImpact: false,
      hasClaimRisk: true,
      claimRiskLevel: 'Medium',
      claimRiskNotes: 'Overdue approval may increase delay claim exposure.',
      responsibleParty: 'Hassan Al-Omari',
      requiredAction: 'Return approved or commented MEP shop drawing',
      actionDueDate: d('2026-05-23'),
      actionStatus: 'Waiting for Response',
      nextStep: 'Consultant response required before ceiling works resume.',
      createdBy: 'Fatima Al-Manaseer',
      attachments: [attachment('rec-0006', 'S3-MEP-221 Rev B.dwg', d('2026-05-19'), 'Document Controller')],
    }),
    baseRecord({
      id: 'rec-0007',
      reference: 'CR-2026-008',
      title: 'Claim Risk - Notice for MEP Coordination Delay',
      projectId: 'p1',
      sender: 'Commercial / QS Team',
      receiver: 'Project Manager',
      dateReceived: d('2026-05-24'),
      description: 'Commercial team flagged claim risk because drawing approval has exceeded the due date and Level 3 ceiling works remain blocked. Notice draft prepared with references to CORR-2026-001, EI-2026-015, VAR-2026-014, CI-2026-011, and AP-2026-004.',
      mainCategory: 'Claim Risk',
      subcategory: 'Notice Risk',
      discipline: 'Contract Administration',
      priority: 'Critical',
      status: 'Open',
      eventDate: d('2026-05-24'),
      responseDueDate: d('2026-05-26'),
      linkedVariations: ['rec-0004'],
      linkedDelays: ['rec-0003'],
      linkedInstructions: ['rec-0002'],
      linkedApprovals: ['rec-0006'],
      linkedCostImpacts: ['rec-0005'],
      linkedProgrammeImpacts: ['rec-0003'],
      linkedClaimRisks: [],
      linkedSiteIssues: ['rec-0001'],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: true,
      programmeImpactDesc: 'Delay notice linked to 7-day Level 3 programme impact.',
      hasCostImpact: true,
      costImpactDesc: 'Potential claim includes rework and prolongation exposure.',
      estimatedAmount: 127800,
      hasClaimRisk: true,
      claimRiskLevel: 'Critical',
      claimRiskNotes: 'Issue formal notice before expiry of contract notification period.',
      responsibleParty: 'Ahmed Al-Rashid',
      requiredAction: 'Approve and issue delay/cost notice to consultant',
      actionDueDate: d('2026-05-26'),
      actionStatus: 'Escalated',
      nextStep: 'Project Manager to approve notice wording and send before close of business.',
      createdBy: 'Aisha Al-Masri',
      attachments: [attachment('rec-0007', 'Draft Notice MEP Coordination Delay.pdf', d('2026-05-24'), 'Commercial / QS Team')],
    }),
    baseRecord({
      id: 'rec-0008',
      reference: 'DLY-2026-021',
      title: 'Procurement Delay - Imported Facade Brackets',
      projectId: 'p2',
      sender: 'Main Contractor',
      receiver: 'Planning Team',
      dateReceived: d('2026-04-03'),
      description: 'Facade bracket shipment delayed at Aqaba port pending customs clearance. Planner identified impact to villa block facade start and requested recovery sequence from procurement.',
      mainCategory: 'Procurement',
      subcategory: 'Procurement Delay',
      discipline: 'Procurement',
      priority: 'High',
      status: 'Open',
      eventDate: d('2026-04-02'),
      responseDueDate: d('2026-04-07'),
      linkedVariations: [],
      linkedDelays: ['rec-0009'],
      linkedInstructions: [],
      linkedApprovals: [],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: ['rec-0009'],
      linkedClaimRisks: [],
      linkedSiteIssues: [],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: true,
      programmeImpactDesc: '5-day risk to facade start on villa block A.',
      hasCostImpact: false,
      hasClaimRisk: false,
      responsibleParty: 'Mohammed Al-Dajani',
      requiredAction: 'Confirm customs release date and recovery sequence',
      actionDueDate: d('2026-04-07'),
      actionStatus: 'Open',
      nextStep: 'Procurement to submit updated delivery note and planner to resequence facade works.',
      createdBy: 'Fatima Al-Manaseer',
      attachments: [attachment('rec-0008', 'Facade Bracket Shipping Notice.pdf', d('2026-04-03'), 'Main Contractor')],
    }),
    baseRecord({
      id: 'rec-0009',
      reference: 'PRG-2026-022',
      title: 'Programme Update - Facade Bracket Recovery Plan',
      projectId: 'p2',
      sender: 'Planning Team',
      receiver: 'Project Manager',
      dateReceived: d('2026-04-06'),
      description: 'Programme team issued recovery option to shift manpower to pool plantroom rough-in while facade brackets clear customs. Remaining risk is 3 days if release occurs by 9 April.',
      mainCategory: 'Programme Impact',
      subcategory: 'Programme Update',
      discipline: 'Planning',
      priority: 'Medium',
      status: 'In Review',
      eventDate: d('2026-04-06'),
      responseDueDate: d('2026-04-09'),
      linkedVariations: [],
      linkedDelays: [],
      linkedInstructions: [],
      linkedApprovals: [],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: [],
      linkedClaimRisks: [],
      linkedSiteIssues: [],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: ['rec-0008'],
      linkedPayments: [],
      hasProgrammeImpact: true,
      programmeImpactDesc: '3 to 5 day facade start risk after mitigation.',
      hasCostImpact: false,
      hasClaimRisk: false,
      responsibleParty: 'Mohammed Al-Dajani',
      requiredAction: 'Approve recovery sequence and monitor customs release',
      actionDueDate: d('2026-04-09'),
      actionStatus: 'Pending Review',
      nextStep: 'Project Manager to accept mitigation sequence.',
      createdBy: 'Mohammed Al-Dajani',
      attachments: [attachment('rec-0009', 'Aqaba Programme Recovery Rev 03.pdf', d('2026-04-06'), 'Planning Team')],
    }),
    baseRecord({
      id: 'rec-0010',
      reference: 'NCR-2026-005',
      title: 'NCR - Waterproofing Membrane Lap Joint Failure',
      projectId: 'p2',
      sender: 'Quality Team',
      receiver: 'Consultant / Engineer',
      dateReceived: d('2026-04-11'),
      description: 'QA/QC inspection found failed membrane lap joints at podium transfer slab. Engineer requested corrective method statement and photo evidence before flood test acceptance.',
      mainCategory: 'Quality/NCR',
      subcategory: 'NCR Follow-up',
      discipline: 'QA/QC',
      priority: 'High',
      status: 'Pending Response',
      eventDate: d('2026-04-10'),
      responseDueDate: d('2026-04-14'),
      linkedVariations: [],
      linkedDelays: [],
      linkedInstructions: [],
      linkedApprovals: ['rec-0011'],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: [],
      linkedClaimRisks: [],
      linkedSiteIssues: [],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: false,
      hasCostImpact: false,
      hasClaimRisk: false,
      responsibleParty: 'Hassan Al-Omari',
      requiredAction: 'Submit corrective action evidence for waterproofing NCR',
      actionDueDate: d('2026-04-14'),
      actionStatus: 'Waiting for Response',
      nextStep: 'Quality team to upload repair photos and signed inspection request.',
      createdBy: 'Fatima Al-Manaseer',
      attachments: [attachment('rec-0010', 'NCR-005 Waterproofing Photos.jpg', d('2026-04-11'), 'Quality Team')],
    }),
    baseRecord({
      id: 'rec-0011',
      reference: 'AP-2026-018',
      title: 'Approval - Waterproofing Corrective Action',
      projectId: 'p2',
      sender: 'Consultant / Engineer',
      receiver: 'Main Contractor',
      dateReceived: d('2026-04-15'),
      description: 'Engineer accepted the waterproofing corrective action after repair photos and inspection record were submitted. Flood test can proceed after 24-hour curing period.',
      mainCategory: 'Approval',
      subcategory: 'Method Statement Approval',
      discipline: 'QA/QC',
      priority: 'Medium',
      status: 'Closed',
      eventDate: d('2026-04-15'),
      responseDueDate: d('2026-04-15'),
      closureDate: d('2026-04-15'),
      linkedVariations: [],
      linkedDelays: [],
      linkedInstructions: [],
      linkedApprovals: [],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: [],
      linkedClaimRisks: [],
      linkedSiteIssues: [],
      linkedRFIs: [],
      linkedNCRs: ['rec-0010'],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: false,
      hasCostImpact: false,
      hasClaimRisk: false,
      responsibleParty: 'Hassan Al-Omari',
      requiredAction: 'Archive accepted NCR close-out package',
      actionDueDate: d('2026-04-15'),
      actionStatus: 'Closed',
      nextStep: 'Closed - include in QA/QC handover file.',
      createdBy: 'Hassan Al-Omari',
      attachments: [attachment('rec-0011', 'Waterproofing NCR Closeout.pdf', d('2026-04-15'), 'Consultant / Engineer')],
    }),
    baseRecord({
      id: 'rec-0012',
      reference: 'RFI-2026-031',
      title: 'RFI - ICU Medical Gas Ceiling Coordination',
      projectId: 'p3',
      sender: 'Main Contractor',
      receiver: 'Consultant / Engineer',
      dateReceived: d('2026-03-02'),
      description: 'Contractor requested clarification on medical gas pendant positions in ICU rooms because architectural reflected ceiling plans conflict with MEP builder work drawings.',
      mainCategory: 'RFI/Submittal',
      subcategory: 'Design Clarification',
      discipline: 'MEP',
      priority: 'High',
      status: 'Open',
      eventDate: d('2026-03-01'),
      responseDueDate: d('2026-03-06'),
      linkedVariations: [],
      linkedDelays: [],
      linkedInstructions: ['rec-0013'],
      linkedApprovals: [],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: [],
      linkedClaimRisks: [],
      linkedSiteIssues: [],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: false,
      hasCostImpact: false,
      hasClaimRisk: false,
      responsibleParty: 'Hassan Al-Omari',
      requiredAction: 'Respond to ICU ceiling coordination RFI',
      actionDueDate: d('2026-03-06'),
      actionStatus: 'Open',
      nextStep: 'Engineer to issue coordinated reflected ceiling response.',
      createdBy: 'Fatima Al-Manaseer',
      attachments: [attachment('rec-0012', 'RFI-031 ICU Ceiling Markup.pdf', d('2026-03-02'), 'Main Contractor')],
    }),
    baseRecord({
      id: 'rec-0013',
      reference: 'EI-2026-024',
      title: "Engineer's Instruction - ICU Ceiling Pendant Set-Out",
      projectId: 'p3',
      sender: 'Consultant / Engineer',
      receiver: 'Main Contractor',
      dateReceived: d('2026-03-05'),
      description: 'Engineer confirmed pendant set-out and instructed contractor to coordinate ceiling access panels with medical gas supplier. Instruction closes RFI-031 with revised room-by-room coordinates.',
      mainCategory: 'Instruction',
      subcategory: 'Design Instruction',
      discipline: 'MEP',
      priority: 'Medium',
      status: 'Closed',
      eventDate: d('2026-03-05'),
      instructionDate: d('2026-03-05'),
      responseDueDate: d('2026-03-05'),
      closureDate: d('2026-03-05'),
      linkedVariations: [],
      linkedDelays: [],
      linkedInstructions: [],
      linkedApprovals: [],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: [],
      linkedClaimRisks: [],
      linkedSiteIssues: [],
      linkedRFIs: ['rec-0012'],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: false,
      hasCostImpact: false,
      hasClaimRisk: false,
      responsibleParty: 'Hassan Al-Omari',
      requiredAction: 'Coordinate supplier setting-out drawings',
      actionDueDate: d('2026-03-07'),
      actionStatus: 'Closed',
      nextStep: 'Closed - incorporate coordinates into shop drawing revision.',
      createdBy: 'Hassan Al-Omari',
      attachments: [attachment('rec-0013', 'EI-024 ICU Pendant Coordinates.pdf', d('2026-03-05'), 'Consultant / Engineer')],
    }),
    baseRecord({
      id: 'rec-0014',
      reference: 'CI-2026-019',
      title: 'Cost Impact - Medical Gas Ceiling Access Panels',
      projectId: 'p3',
      sender: 'Commercial / QS Team',
      receiver: 'Project Manager',
      dateReceived: d('2026-03-08'),
      description: 'QS recorded minor cost impact for additional ceiling access panels required by EI-024. Record links to RFI-031 and the engineer instruction, not to itself.',
      mainCategory: 'Cost Impact',
      subcategory: 'Additional Cost',
      discipline: 'Commercial',
      priority: 'Medium',
      status: 'In Review',
      eventDate: d('2026-03-08'),
      responseDueDate: d('2026-03-12'),
      linkedVariations: [],
      linkedDelays: [],
      linkedInstructions: ['rec-0013'],
      linkedApprovals: [],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: [],
      linkedClaimRisks: [],
      linkedSiteIssues: [],
      linkedRFIs: ['rec-0012'],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: false,
      hasCostImpact: true,
      costImpactDesc: 'JOD 18,600 for added ceiling access panels and coordination labour.',
      estimatedAmount: 18600,
      hasClaimRisk: false,
      responsibleParty: 'Aisha Al-Masri',
      requiredAction: 'Agree access panel rate with contractor',
      actionDueDate: d('2026-03-12'),
      actionStatus: 'Pending Review',
      nextStep: 'QS to review supplier quotation and issue recommendation.',
      createdBy: 'Aisha Al-Masri',
      attachments: [attachment('rec-0014', 'CI-019 Access Panel Quote.pdf', d('2026-03-08'), 'Commercial / QS Team')],
    }),
    baseRecord({
      id: 'rec-0015',
      reference: 'PAY-2024-044',
      title: 'Payment - Final Account Retention Release',
      projectId: 'p4',
      sender: 'Commercial / QS Team',
      receiver: 'Client Representative',
      dateReceived: d('2024-06-18'),
      description: 'Commercial team submitted final account retention release request after completion certificate and snag close-out records were accepted for the Dead Sea Spa Complex.',
      mainCategory: 'Payment',
      subcategory: 'Interim Payment',
      discipline: 'Commercial',
      priority: 'Low',
      status: 'Closed',
      eventDate: d('2024-06-18'),
      responseDueDate: d('2024-06-25'),
      closureDate: d('2024-06-25'),
      linkedVariations: [],
      linkedDelays: [],
      linkedInstructions: [],
      linkedApprovals: ['rec-0016'],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: [],
      linkedClaimRisks: [],
      linkedSiteIssues: [],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: [],
      hasProgrammeImpact: false,
      hasCostImpact: true,
      costImpactDesc: 'Final retention release recorded for commercial close-out.',
      estimatedAmount: 64000,
      hasClaimRisk: false,
      responsibleParty: 'Aisha Al-Masri',
      requiredAction: 'Archive final account payment certificate',
      actionDueDate: d('2024-06-25'),
      actionStatus: 'Closed',
      nextStep: 'Closed - payment certificate included in final account pack.',
      createdBy: 'Aisha Al-Masri',
      attachments: [attachment('rec-0015', 'Final Retention Release Certificate.pdf', d('2024-06-25'), 'Commercial / QS Team')],
    }),
    baseRecord({
      id: 'rec-0016',
      reference: 'AP-2024-052',
      title: 'Approval - Completion Certificate and Snag Close-Out',
      projectId: 'p4',
      sender: 'Consultant / Engineer',
      receiver: 'Client Representative',
      dateReceived: d('2024-06-20'),
      description: 'Engineer issued completion certificate after all hotel spa snag items were closed and final inspection records were signed by client and contractor representatives.',
      mainCategory: 'Approval',
      subcategory: 'Method Statement Approval',
      discipline: 'Contract Administration',
      priority: 'Low',
      status: 'Closed',
      eventDate: d('2024-06-20'),
      responseDueDate: d('2024-06-20'),
      closureDate: d('2024-06-20'),
      linkedVariations: [],
      linkedDelays: [],
      linkedInstructions: [],
      linkedApprovals: [],
      linkedCostImpacts: [],
      linkedProgrammeImpacts: [],
      linkedClaimRisks: [],
      linkedSiteIssues: [],
      linkedRFIs: [],
      linkedNCRs: [],
      linkedProcurements: [],
      linkedPayments: ['rec-0015'],
      hasProgrammeImpact: false,
      hasCostImpact: false,
      hasClaimRisk: false,
      responsibleParty: 'Ahmed Al-Rashid',
      requiredAction: 'Close project completion decision trail',
      actionDueDate: d('2024-06-20'),
      actionStatus: 'Closed',
      nextStep: 'Closed - handover and final account package complete.',
      createdBy: 'Hassan Al-Omari',
      attachments: [attachment('rec-0016', 'Completion Certificate Signed.pdf', d('2024-06-20'), 'Consultant / Engineer')],
    }),
  ];
}

// Required Actions
export function generateMockActions(records: Record[]): RequiredAction[] {
  const impactType = (record: Record): RequiredAction['impactType'] => {
    if (record.hasClaimRisk) return 'Claim';
    if (record.hasCostImpact) return 'Cost';
    if (record.hasProgrammeImpact) return 'Programme';
    if (record.mainCategory === 'Quality/NCR') return 'Quality';
    return 'Programme';
  };

  return records
    .filter((record) => record.actionStatus)
    .map((record, index) => ({
      id: `act-${String(index + 1).padStart(4, '0')}`,
      title: record.requiredAction || `Review ${record.reference}`,
      recordId: record.id,
      projectId: record.projectId,
      responsiblePerson: record.responsibleParty || 'Project Team',
      dueDate: record.actionDueDate || record.responseDueDate || record.dateReceived,
      priority: record.actionStatus === 'Closed' ? 'Low' : record.priority,
      status: record.actionStatus as RequiredAction['status'],
      impactType: impactType(record),
      nextStep: record.nextStep || 'Review linked record and update status.',
      linkedRecord: record,
    }));
}

// Programme Impacts
export function generateMockProgrammeImpacts(records: Record[]): ProgrammeImpact[] {
  const recordsWithImpact = records.filter((r) => r.hasProgrammeImpact);

  return recordsWithImpact.map((record, index) => {
    const linkedIds = [
      ...record.linkedDelays,
      ...record.linkedInstructions,
      ...record.linkedApprovals,
      ...record.linkedSiteIssues,
    ].filter((id) => id !== record.id);
    const linkedRecords = [record, ...records.filter((item) => linkedIds.includes(item.id))];

    return {
      id: `prog-${String(index + 1).padStart(4, '0')}`,
      recordId: record.id,
      projectId: record.projectId,
      delayReason: record.programmeImpactDesc || 'Programme impact under review',
      eventDate: record.eventDate || new Date(),
      programmeUpdateRef: `PROG-2026-${String(index + 1).padStart(3, '0')}`,
      responsibleParty: record.responsibleParty || 'To be assigned',
      potentialTimeImpact: record.projectId === 'p1' ? '7 days' : '3-5 days',
      responseDueDate: record.responseDueDate || new Date(),
      status: record.status === 'Closed' ? 'Resolved' : record.status === 'In Review' ? 'Under Review' : 'Identified',
      linkedRecords,
    };
  });
}

// Cost Impacts
export function generateMockCostImpacts(records: Record[]): CostImpact[] {
  const recordsWithCost = records.filter((r) => r.hasCostImpact);

  return recordsWithCost.map((record, index) => {
    const linkedIds = [
      ...record.linkedVariations,
      ...record.linkedInstructions,
      ...record.linkedApprovals,
      ...record.linkedPayments,
      ...record.linkedRFIs,
    ].filter((id) => id !== record.id);
    const supportingRecords = [record, ...records.filter((item) => linkedIds.includes(item.id))];

    return {
      id: `cost-${String(index + 1).padStart(4, '0')}`,
      recordId: record.id,
      projectId: record.projectId,
      costImpactType: record.costImpactDesc || 'Additional cost under review',
      estimatedAmount: record.estimatedAmount || 0,
      variationRef: record.linkedVariations[0] ? records.find((item) => item.id === record.linkedVariations[0])?.reference : undefined,
      claimRiskLevel: record.claimRiskLevel || 'Low',
      supportingRecords,
      responsibleParty: record.responsibleParty || 'Commercial Team',
      requiredAction: record.requiredAction || 'Submit detailed cost justification',
      status: record.status === 'Closed' ? 'Closed' : record.status === 'In Review' ? 'Identified' : 'Claimed',
    };
  });
}
